### ISSUE TITLE
Opinião

### ISSUE THREAD

**Issue by willonf** [mauricio-viana/bootcamp-fullstack#22]
Estou pensando em fazer um bootcamp da IGTI. Como são as aulas? É de qualidade mesmo, você aprende bem? Qual o ritmo das aulas? Você recomenda?

Encontrei seu repositório por acaso e resolvi perguntar.

**Comment by mauricio-viana** [comment]
@willonf eu tive uma ótima experiência com a IGTI, você sente a evolução a cada módulo, o conteúdo dos módulos são disponibilizados em vídeos aulas através da plataforma deles, onde facilita o estudo. Para fixar o conteúdo aprendido por módulo, era feito dois projetos em formas de desafios, um trabalho prático e um desafio final, após o término dos projetos os professores faziam uma live codificando a solução e interagindo com a turma, esse momento era muito valioso para esclarecer as dúvidas e trocar experiências.
Bom, eu super recomendo, e espero que a IGTI tenha mantido a qualidade e aperfeiçoado seus cursos!
Abr

**Comment by willonf** [comment]
Entendi. Muito obrigado pela resposta. Será de grande valia para mim. Sucesso!
